### ISSUE TITLE
Cannot build graphy

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#2]
Thanks for graphy, cool stuff. I wanted to try it out, but ran into an issue that I couldn't build and test graphy:

```
> node -v
v7.2.0
> git clone https://github.com/blake-regalia/graphy.js.git;
> cd graphy.js;
> npm run test;

Including source "parser-macros.builder-js"
Reading local file "/graphy.js/lib/flavors/parser-macros.builder-js"
/graphy.js/node_modules/Builder/src/Machine.js:160
          throw e;
          ^

Error: Unclosed @macro statement (parser-macros.builder-js:35)
    at AstParser._parse (/graphy.js/node_modules/Builder/src/AstParser.js:540:15)
    at AstParser._parse (/graphy.js/node_modules/Builder/src/AstParser.js:438:16)
    at AstParser.parse (/graphy.js/node_modules/Builder/src/AstParser.js:59:17)
    at Machine._includeSource (/graphy.js/node_modules/Builder/src/Machine.js:225:29)
    at Machine._executeInclude (/graphy.js/node_modules/Builder/src/Machine.js:189:12)
    at Machine._execute (/graphy.js/node_modules/Builder/src/Machine.js:121:18)
    at Machine.execute (/graphy.js/node_modules/Builder/src/Machine.js:67:10)
    at $.tap (/graphy.js/gulp/parsers.js:24:21)
    at Stream.modifyFile (/graphy.js/node_modules/gulp-tap/lib/tap.js:69:11)
    at Stream.stream.write (/graphy.js/node_modules/through/index.js:26:11)

```

ps. wanted to test and build it from the repo, as I encountered another possible bug, that I couldn't parse an ntriple file that had a literal with no explicit datatype.

**Comment by blake-regalia** [comment]
This is a problem with [Builder](https://github.com/electricimp/Builder) for node >= v6.4.  I noticed this a few weeks ago and have been forced to temporarily switch to 6.3.x while compiling the source. That _should_ fix this issue as a workaround, let me know if it does not work. I'll have to open an issue with Builder or write a new macro compiler all together.

As for parsing literals without a datatype in NTriples format, do you have an input that demonstrates this? I am unable to reproduce it. There does seem to be an NTriples test case that covers this.

**Comment by blake-regalia** [comment]
Build now [working](https://travis-ci.org/blake-regalia/graphy.js) for *nix systems with node.js versions 8, 9, 10, 11.
