### ISSUE TITLE
Fails on literal without datatype

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#3]
Just to continue from #2 :
`<http://somurl> <somotherurl> "functioneelgebied 100000019" .` fails for me. Adding a lang tag or datatype resolves this error

Parser: nt
Version: 2.0.0
Node: v7.2.0

**Comment by LaurensRietveld** [comment]
Oops, forgot to add error msg: 

```
TypeError: Cannot read property 'substr' of undefined
    at Parser.parse_error (/graphytest/node_modules/graphy/dist/nt/parser.js:1:563)
    at ReadStream.<anonymous> (/graphytest/node_modules/graphy/dist/nt/parser.js:1:4235)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1838:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:602:17)



```

**Comment by blake-regalia** [comment]
Confirmed. `R_LITERAL_ESCAPELESS` and `R_LITERAL` regexes only expect typed or lang-tagged literals in nt and nq parsers. Fixed in https://github.com/blake-regalia/graphy.js/commit/086046e13a0b50ac5361a469312db0abc5b075fa
