### ISSUE TITLE
Cannot parse nq file without graphname

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#4]
An nquad file without graph name results in the following error:

```
ReferenceError: i is not defined
    at ReadStream.s (/graphytest/node_modules/graphy/dist/nq/parser.js:1:812)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)


```
For completeness, an example:
`<http://somurl> <http://somotherurl> "asd"@en .`

Version: 2.0.0
Node: v7.2.0

**Comment by blake-regalia** [comment]
Also true and fixed in https://github.com/blake-regalia/graphy.js/commit/ee29f4ae87e9f018a88b55ddf0d4abbead7bc356

I realize now that the nt and nq parsers don't actually have test cases.
