### ISSUE TITLE
Cannot build graphy (node <=6)

### ISSUE THREAD

**Issue by LaurensRietveld** [blake-regalia/graphy.js#7]
When building graphy, I get the following error:

```
 $ node -v
v4.2.6
$ npm run test

> graphy@2.0.0 test /scratch/lrd900/graphy.js
> gulp && gulp test

[11:29:09] Using gulpfile /scratch/lrd900/graphy.js/gulpfile.js
[11:29:09] Starting 'transpile-main-es5'...
[11:29:10] Starting 'copy-main-es6'...
[11:29:10] 'copy-main-es6' errored after 2.27 ms
[11:29:10] Error:
script recipe "copy" has a syntax/runtime error:

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Gulp.<anonymous> (/scratch/lrd900/graphy.js/node_modules/gulp-soda/dist.es5/soda.js:274:18)
    at module.exports (/scratch/lrd900/graphy.js/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/scratch/lrd900/graphy.js/node_modules/orchestrator/index.js:273:3)
[11:29:11] Finished 'transpile-main-es5' after 2.26 s
```

**Comment by blake-regalia** [comment]
The source uses quite a bit ES6 syntax, so to *compile* I recommend at least node v6.x  http://node.green/  -- as stated in [this comment](https://github.com/blake-regalia/graphy.js/issues/2#issuecomment-263018726), v6.3.x works for now.

```
$ npm i -g n
$ n 6.3.1
```

Try it out with that version -- if you get it working, feel free to close this issue.

**Comment by LaurensRietveld** [comment]
jep, that works. later versions (e.g. 6.9) won't because of the builder issue (#2)
